function PSNRshell()
[psnr bpp] = plotPSNR;

plot(bpp(:,1), psnr,'b--',...
    bpp(:,2), psnr,'r-.',...
     bpp(:,3), psnr,'g',...
     bpp(:,4), psnr,'k',...
     bpp(:,5), psnr,'b:');
grid on;
xlabel('bpp');
ylabel('PSNR');
title('image compresion');
legend('multi models','1 model',...
    'Location','NorthWest',...
    'context encoding',...
    'sign context',...
    'context for sign');
    


end
